# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 07:10
from __future__ import unicode_literals

import ckeditor_uploader.fields
import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('url', models.URLField(blank=True, default='')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('logo', models.ImageField(blank=True, upload_to=course.models.course_logo)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('upvotes', models.IntegerField(blank=True, null=True)),
                ('free', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='Select', max_length=20)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitter', to=settings.AUTH_USER_MODEL)),
                ('tech', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='technology.Technology')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
