# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180207_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='abc'),
        ),
    ]
