# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-13 08:18
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20180410_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='abc'),
            preserve_default=False,
        ),
    ]
