# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-13 15:31
from __future__ import unicode_literals

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20180513_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, upload_to=course.models.Course.course_logo),
        ),
        migrations.AddField(
            model_name='course',
            name='logo_url',
            field=models.URLField(default=''),
        ),
    ]
