# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-05 07:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import track_course.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('url', models.URLField(blank=True, default='')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('logo', models.ImageField(blank=True, upload_to=track_course.models.track_course_logo)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('medium', models.CharField(choices=[('VIDEO', 'Video'), ('TEXT', 'Text')], default='Select', max_length=20)),
                ('free', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='Select', max_length=20)),
                ('track', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='track.Track')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
