# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_course', '0002_auto_20180606_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcourse',
            name='number',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
