# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_course', '0003_trackcourse_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcourse',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
