# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import technology.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('detail', models.TextField(blank=True)),
                ('doc_url', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, upload_to=technology.models.tech_logo)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('course_count', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
