# Generated by Django 2.0.2 on 2018-02-07 10:50

from django.db import migrations, models
import technology.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True)),
                ('doc_url', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, upload_to=technology.models.Technology.tech_logo)),
                ('logo_url', models.URLField(default='')),
            ],
        ),
    ]
