# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='versions',
            name='tech',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='technology.Technology'),
        ),
    ]
