# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_auto_20180309_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
