# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0003_auto_20180309_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
